const doctors = [
  {
    id: "1",
    firstname: "Kate",
    lastname: "Kate",
    professional: "Dentist",
    title: "Dentist",
    image: require("../assets/female_dentist.png"),
    avatar: require("../assets/female_dentist.png"),
    description: "B.D.S, M.D.S",
    experiences: "5 years",
    greeting:
      "Hi I am Dr Kate Williams, a dentist by profession with over 5 years of practice in handling critical dental procedures",
  },
  {
    id: "2",
    firstname: "Jimi",
    lastname: "Johnson",
    professional: "Physician",
    title: "GP",
    image: require("../assets/male_physician.png"),
    avatar: require("../assets/male_physician.png"),
    description: "Doctor of the highest qualification category",
    experiences: "25 years",
    greeting:
      "Hi, my name is Jimi Johnson, I am a Physician. I have 25 years experience in this field that I promise I can help you with your health problems",
  },
  {
    id: "3",
    firstname: "Ellinore",
    lastname: "de Roos",
    professional: "Dermatologist",
    title: "Dermatologist",
    image: require("../assets/female_dermatologist.png"),
    avatar: require("../assets/female_dermatologist.png"),
    description: "M.D.",
    experiences: "30 years",
    greeting:
      "Hi, my name is Elllinore and I am a Dermatologist. I have 30 years experience in treating skin and hair conditions.I can help you improve your current skin health",
  },
  {
    id: "4",
    firstname: "David",
    lastname: "Brown",
    professional: "Chiropractor",
    title: "Chiropractor",
    image: require("../assets/chiropractor.png"),
    avatar: require("../assets/chiropractor.png"),
    description: "B.S., D.C.",
    experiences: "20 years",
    greeting:
      "Hi, my name is David, a chiropractor by profession. I am experienced in restoring mobility, sport injury, back pain and other posture related problems. I have 20 years of practice in this field.",
  },
  {
    id: "5",
    firstname: "Marry",
    lastname: "Shawn",
    professional: "Obstetrician-Gynaecologist",
    title: "Gynaecologist",
    image: require("../assets/gynac.png"),
    avatar: require("../assets/gynac.png"),
    description: "M.S., D.O.",
    experiences: "28 years",
    greeting:
      "Hi, my name is Marry Shawn, I have 28 years experience of practicing as a gynaecologist. I have treated many patients with cases of infertility, pelvic issues, reconstructive surgeries and maternal care.",
  },
  {
    id: "6",
    firstname: "Zuan",
    lastname: "Phaang",
    professional: "Eye Specialist",
    title: "Opthalmologist",
    image: require("../assets/eyedoctor.png"),
    avatar: require("../assets/eyedoctor.png"),
    description: "Doctor of the highest qualification category",
    experiences: "12 years",
    greeting:
      "Hi, my name is Zuan  and I am an opthalmologist, your eye care specialist. I have 12 years experience.",
  },
  {
    id: "7",
    firstname: "Natasha",
    lastname: "Sharma",
    professional: "Dentist",
    title: "Herbal",
    image: require("../assets/female_dentist.png"),
    avatar: require("../assets/female_dentist.png"),
    description: "Doctor of the highest qualification category",
    experiences: "10 years",
    greeting:
      "Hi, my name is Natasha, a dentist with 16 years experience. I have treated cases of periodontal, edentulism, oral cancer, cleft lip, noma etc. You can trust me with your oral health.",
  },
  {
    id: "8",
    firstname: "Tylor",
    lastname: "Wrick",
    professional: "Skin Specialist",
    title: "Dermatologist",
    image: require("../assets/male_dermatologist.png"),
    avatar: require("../assets/male_dermatologist.png"),
    description: "Doctor of the highest qualification category",
    experiences: "23 years",
    greeting:
      "Hi, my name is Tylor Wrick and by profession I am a Dermatologist. I have 23 years experience in treating skin and hair problems.",
  },
  {
    id: "9",
    firstname: "Billi",
    lastname: "Smith",
    professional: "Urologist",
    title: "Urologist",
    image: require("../assets/urologist.png"),
    avatar: require("../assets/urologist.png"),
    description: "Doctor of the highest qualification category",
    experiences: "30 years",
    greeting:
      "I am Billi Smith, a Urologist with 31 years of experience in this area. I have diagnosed and helped many patients with problems in kidneys, ureter, bladder or prostate.",
  },
  {
    id: "10",
    firstname: "Jarred",
    lastname: "Shine",
    professional: "Surgeon",
    title: "Surgeon",
    image: require("../assets/surgeon.png"),
    avatar: require("../assets/surgeon.png"),
    description: "Doctor of the highest qualification category",
    experiences: "38 years",
    greeting:
      "Hi, my name is Jarred Shine and I am a Surgeon. I have 38 years experience in this area that I promise I can help you with your health problems",
  },
  {
    id: "11",
    firstname: "Smitha",
    lastname: "Gopal",
    professional: "Surgeon",
    title: "Surgeon",
    image: require("../assets/surgeon.png"),
    avatar: require("../assets/surgeon.png"),
    description: "Doctor of the highest qualification category",
    experiences: "22 years",
    greeting:
      "Hi, my name is Smitha Gopal and by profession i am a Surgeon. I have 22 years experience in this area.",
  },
  {
    id: "12",
    firstname: "Ziva",
    lastname: "Stone",
    professional: "GP",
    title: "GP",
    image: require("../assets/female_physician.png"),
    avatar: require("../assets/female_physician.png"),
    description: "Doctor of the highest qualification category",
    experiences: "15 years",
    greeting:
      "Hi, my name is Ziva, I am a Physician. I have been in this profession for 15 years now and I have helped 1000s of patients.",
  },
  {
    id: "13",
    firstname: "Kelvin",
    lastname: "C",
    professional: "Physiotherepist",
    title: "Physiotherepist",
    image: require("../assets/physio.png"),
    avatar: require("../assets/physio.png"),
    description: "Doctor of the highest qualification category",
    experiences: "21 years",
    greeting:
      "Hi, my name is Kelvin C, a medical professional, specialized in  Physiotherepy. I am known to assist patients restore their movement and recover from injuries.",
  },
  {
    id: "14",
    firstname: "Ziva",
    lastname: "Stone",
    professional: "Physician",
    title: "Physician",
    image: require("../assets/female_physician.png"),
    avatar: require("../assets/female_physician.png"),
    description: "Doctor of the highest qualification category",
    experiences: "15 years",
    greeting:
      "Hi, my name is Ziva, I am a Physician. I have been in this profession for 15 years now and I have helped 1000s of patients.",
  },
  {
    id: "15",
    firstname: "Kelvin",
    lastname: "C",
    professional: "Physiotherepist",
    title: "Physiotherepist",
    image: require("../assets/physio.png"),
    avatar: require("../assets/physio.png"),
    description: "Doctor of the highest qualification category",
    experiences: "21 years",
    greeting:
      "Hi, my name is Kelvin C, a medical professional, specialized in  Physiotherepy. I am known to assist patients restore their movement and recover from injuries.",
  },
];

export default doctors;
